
trigger:
- main

resources:
  repositories:
  - repository: script
    type: github
    name: tanchunhau/script
    ref: refs/heads/main
    endpoint: smartracks
  - repository: rcu-service
    type: github
    name: tanchunhau/rcu-service
    ref: refs/heads/main
    endpoint: smartracks
  - repository: smartracks-manifest
    type: github
    name: tanchunhau/smartracks-manifest
    ref: refs/heads/main
    endpoint: smartracks
  - repository: meta-smartracks
    type: github
    name: tanchunhau/meta-smartracks
    ref: refs/heads/main
    endpoint: smartracks
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracks-build:0.3
    options:
    volumes:
    - /mnt:/mnt

jobs:
 - template: pipeline/steps.yml@script
