
trigger:
- main

resources:
  repositories:
  - repository: rcu-service
    type: github
    name: tanchunhau/rcu-service
    endpoint: SmartRacks
  - repository: smartracks-manifest
    type: github
    name: tanchunhau/smartracks-manifest
    endpoint: SmartRacks
  - repository: meta-smartracks
    type: github
    name: tanchunhau/meta-smartracks
    endpoint: SmartRacks
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracks-build:0
    options:
    volumes:
    - /mnt:/mnt
         
jobs:
- job: OpenEmbedded Build & Export
  container: smartracks-build
  timeoutInMinutes: 3600
  pool:
    name: Drivers-NIBuildFarm-RFMIBUILD
    demands:
      - docker
      - Agent.OS -equals Linux
  
  steps:
  - script: |
      repo init -u https://github.com/tanchunhau/smartracks-manifest.git -b main -m smartracks-manifest.xml
      repo sync
      . export
      bitbake smartracks-minimal-image
      cd deploy/images/apalis-imx8x-smartracks
      mkdir -p build-$(Build.BuildNumber)
      cp $(find . -name 'Apalis-iMX8X-SmartRacks_Reference-Minimal-Image-rt-Tezi_*.tar') build-$(Build.BuildNumber)
      cp -R build-$(Build.BuildNumber) /mnt/nirvana/perforceExports/smartracks/testing123
