
trigger:
- main

resources:
  repositories:
  - repository: rcu-service
    type: github
    name: tanchunhau/rcu-service
    endpoint: smartracks
  - repository: smartracks-manifest
    type: github
    name: tanchunhau/smartracks-manifest
    endpoint: smartracks
  - repository: meta-smartracks
    type: github
    name: tanchunhau/meta-smartracks
    endpoint: smartracks
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracks-build:1
    options:
    volumes:
    - /mnt:/mnt
         
jobs:
- job: OpenEmbedded_Build_And_Export
  container: smartracks-build
  timeoutInMinutes: 3600
  pool:
    name: Drivers-NIBuildFarm-RFMIBUILD
    demands:
      - docker
      - Agent.OS -equals Linux
  
  steps:
  - checkout: smartracks-manifest
  - checkout: rcu-service
  - script: |
      #cd /home/rfmibuild_azpcontainer/rcu-service
      #ls  -la
      rm -r .repo
      repo init -u https://github.com/tanchunhau/smartracks-manifest.git -b main -m smartracks-manifest.xml
      ls  -la
      #cd smartracks-manifest
      #ls  -1
      #repo init -u $(Build.SourcesDirectory)/smartracks-manifest -b main -m smartracks-manifest.xml
      #cd $(Build.SourcesDirectory)/smartracks-manifest
      #repo init -m ./repo/smartracks-manifest.xml
      #repo init -u ~/bin/repo/smartracks-manifest/smartracks-manifest.xml
      #repo init -m smartracks-manifest.xml
      #repo init -m /home/rfmibuild_azpcontainer/smartracks-manifest.xml
      #repo init -u https://github.com/tanchunhau/smartracks-manifest.git -b main -m smartracks-manifest.xml
      repo sync
      . export
      #bitbake rcu-service
      bitbake smartracks-minimal-image
      #mkdir -p build-$(Build.BuildNumber)
      #cp deploy/images/apalis-imx8x-smartracks/$(find . -name 'Apalis-iMX8X-SmartRacks_Reference-Minimal-Image-rt-Tezi_*.tar') build-$(Build.BuildNumber)
      #cp -R build-$(Build.BuildNumber) /mnt/nirvana/perforceExports/smartracks/testing123
      #
      
