
trigger:
- main

resources:
  repositories:
  - repository: rcu-service
    type: github
    name: tanchunhau/rcu-service
    endpoint: SmartRacks
  - repository: smartracks-manifest
    type: github
    name: tanchunhau/smartracks-manifest
    endpoint: SmartRacks
  - repository: meta-smartracks
    type: github
    name: tanchunhau/meta-smartracks
    endpoint: SmartRacks
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracks-build:0
    options:
    volumes:
    - /mnt:/mnt
         
jobs:
- job: Build_OpenEmbedded
  container: smartracks-build
  timeoutInMinutes: 3600
  pool:
    name: Drivers-NIBuildFarm-RFMIBUILD
    demands:
      - docker
      - Agent.OS -equals Linux
  
  steps:
  - checkout: self
    submodules: true
  - checkout: smartracks-manifest
  - script: |
      repo init -u https://github.com/tanchunhau/smartracks-manifest.git -b main -m smartracks-manifest.xml
      repo sync
      . export
      bitbake smartracks-minimal-image
      mkdir -p /mnt/nirvana/perforceExports/smartracks/testing123/build-$(Build.BuildNumber)
      cp deploy/images/apalis-imx8x/toradexlinux.tng /mnt/nirvana/perforceExports/smartracks/testing123/build-$(Build.BuildNumber)
      cp deploy/images/apalis-imx8x/Apalis-iMX8X_Reference-Minimal-Image-rt-Tezi_5.1.0-devel-20201222130932+build.0.tar /mnt/nirvana/perforceExports/smartracks/testing123/build-$(Build.BuildNumber)
