
trigger:
- main

resources:
  repositories:
  - repository: script
    type: github
    name: tanchunhau/script
    ref: refs/heads/main
    endpoint: smartracks


resources:
 - template: pipeline/steps.yml@script
