
trigger:
- main

resources:
  repositories:
  - repository: script
    type: github
    name: tanchunhau/script
    ref: refs/heads/main
    endpoint: smartracks

jobs: 
    - template: pipeline/steps.yml@{script}
