
trigger:
- main

resources:
  repositories:
  - repository: rcu-service
    type: github
    name: tanchunhau/rcu-service
    endpoint: smartracks
  - repository: smartracks-manifest
    type: github
    name: tanchunhau/smartracks-manifest
    endpoint: smartracks
  - repository: meta-smartracks
    type: github
    name: tanchunhau/meta-smartracks
    endpoint: smartracks
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracks-build:0.3
    options:
    volumes:
    - /mnt:/mnt
         
jobs:
- job: OpenEmbedded_Build_And_Export
  container: smartracks-build
  timeoutInMinutes: 3600
  pool:
    name: Drivers-NIBuildFarm-RFMIBUILD
    demands:
      - docker
      - Agent.OS -equals Linux
  
  steps:
  - checkout: smartracks-manifest
  - checkout: rcu-service
  - checkout: meta-smartracks
  - script: |
      echo "-1-"
      #sed -i 's|PathToBeDefine|$(Build.SourcesDirectory)/smartracks-manifest|g' $(Build.SourcesDirectory)/smartracks-manifest/layers/meta-smartracks/recipes-core/rcu-service/rcu-service_1.0.bb
      #cat $(Build.SourcesDirectory)/smartracks-manifest/layers/meta-smartracks/recipes-core/rcu-service/rcu-service_1.0.bb
      rm -r .repo
      ls -la
      cd $(Build.SourcesDirectory)/smartracks-manifest
      git branch
      git checkout -b main
      repo init -u $(Build.SourcesDirectory)/smartracks-manifest -b main -m smartracks-manifest.xml
      repo sync
      rm -r layers/meta-smartracks
      cp  -r $(Build.SourcesDirectory)/meta-smartracks $(Build.SourcesDirectory)/smartracks-manifest/layers
      sed -i 's|PathToBeDefine|$(Build.SourcesDirectory)|g' $(Build.SourcesDirectory)/smartracks-manifest/layers/meta-smartracks/recipes-core/rcu-service/rcu-service_1.0.bb
      . export
      #bitbake rcu-service
      bitbake smartracks-minimal-image
      mkdir -p build-$(Build.BuildNumber)
      cp deploy/images/apalis-imx8x-smartracks/$(find . -name 'Apalis-iMX8X-SmartRacks_Reference-Minimal-Image-rt-Tezi_*.tar') build-$(Build.BuildNumber)
      cp -R build-$(Build.BuildNumber) /mnt/nirvana/perforceExports/smartracks/testing123
      
      
      
      
      #repo init -u $(Build.SourcesDirectory)/smartracks-manifest -b main -m smartracks-manifest.xml
      #cd $(Build.SourcesDirectory)/smartracks-manifest
      #repo init -m ./repo/smartracks-manifest.xml
      #repo init -u ~/bin/repo/smartracks-manifest/smartracks-manifest.xml
      #repo init -m smartracks-manifest.xml
      #repo init -m /home/rfmibuild_azpcontainer/smartracks-manifest.xml
      #repo init -u https://github.com/tanchunhau/smartracks-manifest.git -b main -m smartracks-manifest.xml
      #repo init
       
      #repo sync -m  $(Build.SourcesDirectory)/smartracks-manifest/smartracks-manifest.xml
      
      
  
      #bitbake rcu-service
      #bitbake smartracks-minimal-image
      #mkdir -p build-$(Build.BuildNumber)
      #cp deploy/images/apalis-imx8x-smartracks/$(find . -name 'Apalis-iMX8X-SmartRacks_Reference-Minimal-Image-rt-Tezi_*.tar') build-$(Build.BuildNumber)
      #cp -R build-$(Build.BuildNumber) /mnt/nirvana/perforceExports/smartracks/testing123
      #
      
